create table person (
    id serial primary key,
    username varchar(30) unique not null,
    passwrd varchar(30) not null,
    first_name varchar(30) not null,
    last_name varchar(30) not null
);


create table artist (
    id serial primary key,
    stage_name varchar(250) not null
);

create table album (
    id serial primary key,
    title varchar(250) not null,
    artist_id integer references artist(id)
);

create table inventory (
    person_id integer references person(id),
    album_id integer references album(id),
    primary key(person_id, album_id)
);

create table apikey (
    id integer references person(id),
    apikey varchar(14),
    primary key(id)
);



insert into person (username, passwrd, first_name, last_name) values ('pslyde0', 'x1Uul6CETGe', 'Portie', 'Slyde');
insert into person (username, passwrd, first_name, last_name) values ('cjeromson1', 'D2z3rRuX4zPM', 'Clarabelle', 'Jeromson');
insert into person (username, passwrd, first_name, last_name) values ('rlarn2', 'y6Rs65jIE', 'Renaldo', 'Larn');
insert into person (username, passwrd, first_name, last_name) values ('abraddon3', 'PyTItu', 'Alameda', 'Braddon');
insert into person (username, passwrd, first_name, last_name) values ('lzanini4', '7iFyUp3', 'Les', 'Zanini');
insert into person (username, passwrd, first_name, last_name) values ('gtofanini5', 'D5rEeQsU', 'Grazia', 'Tofanini');
insert into person (username, passwrd, first_name, last_name) values ('chansbury6', 'fGmHQdsbCNcX', 'Carmine', 'Hansbury');
insert into person (username, passwrd, first_name, last_name) values ('tpoleykett7', '4bY9zYVu', 'Tarah', 'Poleykett');
insert into person (username, passwrd, first_name, last_name) values ('lruggier8', 'TtY4vpp', 'Livia', 'Ruggier');
insert into person (username, passwrd, first_name, last_name) values ('sbarribal9', '8hsvHLwe', 'Sandy', 'Barribal');
insert into person (username, passwrd, first_name, last_name) values ('fmuirheada', '0AaEmwR0', 'Fanya', 'Muirhead');
insert into person (username, passwrd, first_name, last_name) values ('awalczakb', 'rMcdLFWMReP', 'Artur', 'Walczak');
insert into person (username, passwrd, first_name, last_name) values ('bbrightiec', 'y4FbVeiJMgQ0', 'Becka', 'Brightie');
insert into person (username, passwrd, first_name, last_name) values ('lduchartd', 'hhtqq7rQU', 'Langsdon', 'Duchart');
insert into person (username, passwrd, first_name, last_name) values ('jolivelloe', 'XmhDOT3', 'Jeanna', 'Olivello');
insert into person (username, passwrd, first_name, last_name) values ('hdevereuf', 'AXdbkqHx', 'Heath', 'Devereu');
insert into person (username, passwrd, first_name, last_name) values ('ogemnettg', 'N4wbXSWewd4', 'Oriana', 'Gemnett');
insert into person (username, passwrd, first_name, last_name) values ('vdouberdayh', 'pT2kuUjm6oj', 'Verne', 'Douberday');
insert into person (username, passwrd, first_name, last_name) values ('abatchelori', 'hm5maTNQzrR2', 'Annelise', 'Batchelor');
insert into person (username, passwrd, first_name, last_name) values ('abelvinj', 't3k9InQj', 'Antonius', 'Belvin');
insert into person (username, passwrd, first_name, last_name) values ('smoatk', 'GkQC5xSIm', 'Sasha', 'Moat');
insert into person (username, passwrd, first_name, last_name) values ('fnasebyl', 'SSF3ZN', 'Felicle', 'Naseby');
insert into person (username, passwrd, first_name, last_name) values ('hlongstaffm', 'b3V3QBdYcDh4', 'Happy', 'Longstaff');
insert into person (username, passwrd, first_name, last_name) values ('zgearen', 'xVSQY06bJl', 'Zak', 'Geare');
insert into person (username, passwrd, first_name, last_name) values ('lgiraulto', '8oOTI1e', 'Lonnard', 'Girault');
insert into person (username, passwrd, first_name, last_name) values ('ekempsterp', 'lEHrWso6aI', 'Eydie', 'Kempster');
insert into person (username, passwrd, first_name, last_name) values ('fberthomeq', 'vE6oTN9zTAQK', 'Flory', 'Berthome');
insert into person (username, passwrd, first_name, last_name) values ('fwrinchr', 'jpx2aKJ7gP', 'Frazer', 'Wrinch');
insert into person (username, passwrd, first_name, last_name) values ('eskeths', 'iFd17bgW', 'Erhard', 'Sketh');
insert into person (username, passwrd, first_name, last_name) values ('hmufft', 'YsUCnEUSJk', 'Harris', 'Muff');
insert into person (username, passwrd, first_name, last_name) values ('aimoreu', 'zpI0Ze', 'Alyssa', 'Imore');
insert into person (username, passwrd, first_name, last_name) values ('rmaccostov', 'w0WWcIbN4qE', 'Raddy', 'MacCosto');
insert into person (username, passwrd, first_name, last_name) values ('clawlorw', '34O9be', 'Carmon', 'Lawlor');
insert into person (username, passwrd, first_name, last_name) values ('aschachterx', 'cDhX6c0jO', 'Adamo', 'Schachter');
insert into person (username, passwrd, first_name, last_name) values ('bwilkennsony', 'zi9EYe8', 'Belvia', 'Wilkennson');
insert into person (username, passwrd, first_name, last_name) values ('dwoloschinz', 'C1PkuXA3zpa', 'Darlleen', 'Woloschin');
insert into person (username, passwrd, first_name, last_name) values ('avarker10', '91bc0xyH5qKS', 'Ashli', 'Varker');
insert into person (username, passwrd, first_name, last_name) values ('cmurie11', 'vLzPqw2PthK', 'Cicely', 'Murie');
insert into person (username, passwrd, first_name, last_name) values ('tcrammy12', 'FGl0FtXaoU', 'Tabatha', 'Crammy');
insert into person (username, passwrd, first_name, last_name) values ('enelson13', 'Nui93oRt7wej', 'Eziechiele', 'Nelson');
insert into person (username, passwrd, first_name, last_name) values ('imcconachie14', 'cfaY9knxcoZ', 'Isaiah', 'McConachie');
insert into person (username, passwrd, first_name, last_name) values ('ploadman15', 'v53wLP', 'Patin', 'Loadman');
insert into person (username, passwrd, first_name, last_name) values ('kireland16', 'Z7AhdHmzwDyB', 'Kory', 'Ireland');
insert into person (username, passwrd, first_name, last_name) values ('mhillitt17', 'Ld8fOZeq1P5j', 'Myca', 'Hillitt');
insert into person (username, passwrd, first_name, last_name) values ('lbagnold18', 'fzYkZOYzp', 'Lyndsey', 'Bagnold');
insert into person (username, passwrd, first_name, last_name) values ('fpasso19', 'QJaiAHy1j', 'Florri', 'Passo');
insert into person (username, passwrd, first_name, last_name) values ('kcoleman1a', 'qfpUqz9pr', 'Kingston', 'Coleman');
insert into person (username, passwrd, first_name, last_name) values ('prothon1b', 'DPCOdqv9KQh', 'Park', 'Rothon');
insert into person (username, passwrd, first_name, last_name) values ('jmitchener1c', 'eHekVy', 'Joella', 'Mitchener');
insert into person (username, passwrd, first_name, last_name) values ('bcary1d', 'Zmzatw', 'Bevin', 'Cary');


insert into artist (stage_name) values ('Triple-buffered 24/7 artificial intelligence');
insert into artist (stage_name) values ('Networked global portal');
insert into artist (stage_name) values ('Synchronised didactic orchestration');
insert into artist (stage_name) values ('De-engineered incremental Graphical User Interface');
insert into artist (stage_name) values ('Front-line web-enabled Graphic Interface');
insert into artist (stage_name) values ('Down-sized needs-based core');
insert into artist (stage_name) values ('Diverse web-enabled process improvement');
insert into artist (stage_name) values ('Synergized even-keeled conglomeration');
insert into artist (stage_name) values ('Digitized non-volatile hierarchy');
insert into artist (stage_name) values ('Synergized zero tolerance encoding');
insert into artist (stage_name) values ('Monitored neutral initiative');
insert into artist (stage_name) values ('Reactive dedicated productivity');
insert into artist (stage_name) values ('Enhanced dynamic secured line');
insert into artist (stage_name) values ('Public-key hybrid toolset');
insert into artist (stage_name) values ('Object-based impactful neural-net');
insert into artist (stage_name) values ('Compatible 3rd generation local area network');
insert into artist (stage_name) values ('Multi-channelled executive capability');
insert into artist (stage_name) values ('Automated fresh-thinking installation');
insert into artist (stage_name) values ('Enterprise-wide demand-driven definition');
insert into artist (stage_name) values ('Up-sized empowering moderator');
insert into artist (stage_name) values ('Adaptive 4th generation hardware');
insert into artist (stage_name) values ('Reverse-engineered global capacity');
insert into artist (stage_name) values ('Profit-focused real-time knowledge user');
insert into artist (stage_name) values ('Universal heuristic hardware');
insert into artist (stage_name) values ('Open-architected fault-tolerant challenge');
insert into artist (stage_name) values ('Progressive intermediate software');
insert into artist (stage_name) values ('Reactive homogeneous alliance');
insert into artist (stage_name) values ('Enterprise-wide executive leverage');
insert into artist (stage_name) values ('Enhanced bandwidth-monitored frame');
insert into artist (stage_name) values ('Function-based scalable toolset');
insert into artist (stage_name) values ('Progressive leading edge hub');
insert into artist (stage_name) values ('Open-architected intangible challenge');
insert into artist (stage_name) values ('Balanced zero administration monitoring');
insert into artist (stage_name) values ('Re-contextualized transitional benchmark');
insert into artist (stage_name) values ('Future-proofed holistic software');
insert into artist (stage_name) values ('Monitored scalable architecture');
insert into artist (stage_name) values ('Enterprise-wide didactic help-desk');
insert into artist (stage_name) values ('Synergistic next generation artificial intelligence');
insert into artist (stage_name) values ('Extended reciprocal access');
insert into artist (stage_name) values ('Front-line demand-driven artificial intelligence');
insert into artist (stage_name) values ('Customer-focused optimizing contingency');
insert into artist (stage_name) values ('Reduced bandwidth-monitored challenge');
insert into artist (stage_name) values ('Programmable analyzing functionalities');
insert into artist (stage_name) values ('Cloned mission-critical firmware');
insert into artist (stage_name) values ('Public-key client-driven definition');
insert into artist (stage_name) values ('Expanded didactic local area network');
insert into artist (stage_name) values ('Diverse hybrid customer loyalty');
insert into artist (stage_name) values ('Centralized background attitude');
insert into artist (stage_name) values ('Streamlined responsive moderator');
insert into artist (stage_name) values ('Re-engineered encompassing monitoring');


insert into album (title, artist_id) values ('Girl, The', 1);
insert into album (title, artist_id) values ('Brighton Beach Memoirs', 50);
insert into album (title, artist_id) values ('Breathless', 41);
insert into album (title, artist_id) values ('Men, Women & Children', 2);
insert into album (title, artist_id) values ('St. Trinian''s', 20);
insert into album (title, artist_id) values ('Strange Door, The', 14);
insert into album (title, artist_id) values ('Season of the Witch', 15);
insert into album (title, artist_id) values ('Åsa-Nisse - Wälkom to Knohult', 5);
insert into album (title, artist_id) values ('Amanece, que no es poco', 25);
insert into album (title, artist_id) values ('Fern flowers (Fleur de fougère)', 9);
insert into album (title, artist_id) values ('Man Who Planted Trees, The (Homme qui plantait des arbres, L'')', 39);
insert into album (title, artist_id) values ('Dial M for Murder', 15);
insert into album (title, artist_id) values ('Seasoning House, The', 30);
insert into album (title, artist_id) values ('One Hundred Mornings', 49);
insert into album (title, artist_id) values ('Bad Timing: A Sensual Obsession', 41);
insert into album (title, artist_id) values ('Atonement', 18);
insert into album (title, artist_id) values ('To Cross the Rubicon', 50);
insert into album (title, artist_id) values ('23 Paces to Baker Street', 28);
insert into album (title, artist_id) values ('Blacula', 41);
insert into album (title, artist_id) values ('Joy Ride', 29);
insert into album (title, artist_id) values ('Repentance (Monanieba)', 6);
insert into album (title, artist_id) values ('Navy Blues', 8);
insert into album (title, artist_id) values ('Bird of Prey', 45);
insert into album (title, artist_id) values ('In Cold Blood', 19);
insert into album (title, artist_id) values ('Chicken Little', 16);
insert into album (title, artist_id) values ('Hangin'' with the Homeboys', 31);
insert into album (title, artist_id) values ('Saawariya', 10);
insert into album (title, artist_id) values ('Üvegtigris', 15);
insert into album (title, artist_id) values ('Playing from the Plate (Grajacy z talerza)', 4);
insert into album (title, artist_id) values ('Someone Marry Barry', 1);
insert into album (title, artist_id) values ('Major Dundee', 2);
insert into album (title, artist_id) values ('Life''s a Breeze', 23);
insert into album (title, artist_id) values ('Pathfinder (Ofelas)', 42);
insert into album (title, artist_id) values ('What! No Beer?', 2);
insert into album (title, artist_id) values ('Macon County Line', 46);
insert into album (title, artist_id) values ('Ed', 37);
insert into album (title, artist_id) values ('Same River Twice, The', 28);
insert into album (title, artist_id) values ('Zozo', 48);
insert into album (title, artist_id) values ('Fast and the Furious, The', 20);
insert into album (title, artist_id) values ('Finger, The (Dedo, El)', 8);
insert into album (title, artist_id) values ('Gazebo, The', 41);
insert into album (title, artist_id) values ('Playing ''In the Company of Men'' (En jouant ''Dans la compagnie des hommes'')', 40);
insert into album (title, artist_id) values ('Ted Bundy', 26);
insert into album (title, artist_id) values ('Rookie of the Year', 19);
insert into album (title, artist_id) values ('Affinity', 35);
insert into album (title, artist_id) values ('Starsky & Hutch', 12);
insert into album (title, artist_id) values ('Day of the Animals', 20);
insert into album (title, artist_id) values ('Grass', 3);
insert into album (title, artist_id) values ('Female Agents (Les femmes de l''ombre)', 34);
insert into album (title, artist_id) values ('The Widow From Chicago', 13);
insert into album (title, artist_id) values ('Promotion, The', 19);
insert into album (title, artist_id) values ('Neighbours', 21);
insert into album (title, artist_id) values ('Murder Most Foul', 32);
insert into album (title, artist_id) values ('Love Torn in Dream (Combat d''amour en songe)', 11);
insert into album (title, artist_id) values ('Visit, The', 22);
insert into album (title, artist_id) values ('Evil (Ondskan)', 5);
insert into album (title, artist_id) values ('Thoughtcrimes', 9);
insert into album (title, artist_id) values ('Hands on a Hard Body', 10);
insert into album (title, artist_id) values ('Spring Break Shark Attack', 25);
insert into album (title, artist_id) values ('Romantics, The', 10);
insert into album (title, artist_id) values ('Border Incident', 12);
insert into album (title, artist_id) values ('Happy-Go-Lucky', 30);
insert into album (title, artist_id) values ('Princess Protection Program', 3);
insert into album (title, artist_id) values ('Waiting for Superman', 31);
insert into album (title, artist_id) values ('Gate of Hell (Jigokumon)', 11);
insert into album (title, artist_id) values ('Duel', 36);
insert into album (title, artist_id) values ('Renaissance Man', 26);
insert into album (title, artist_id) values ('Terror is a Man', 11);
insert into album (title, artist_id) values ('Franklyn', 28);
insert into album (title, artist_id) values ('Whoregasm', 34);
insert into album (title, artist_id) values ('Slacker', 43);
insert into album (title, artist_id) values ('5 Deadly Venoms, The (Wu du) (Five Deadly Venoms)', 5);
insert into album (title, artist_id) values ('Robin and Marian', 27);
insert into album (title, artist_id) values ('Road House', 36);
insert into album (title, artist_id) values ('Lady in White (a.k.a. The Mystery of the Lady in White)', 3);
insert into album (title, artist_id) values ('A.K.', 26);
insert into album (title, artist_id) values ('All I Want (Try Seventeen)', 47);
insert into album (title, artist_id) values ('Champion, The', 7);
insert into album (title, artist_id) values ('Park Row', 43);
insert into album (title, artist_id) values ('Tavarataivas', 22);
insert into album (title, artist_id) values ('Quatermass Xperiment, The', 15);
insert into album (title, artist_id) values ('Belle of the Nineties', 30);
insert into album (title, artist_id) values ('River Wild, The', 35);
insert into album (title, artist_id) values ('Young Americans, The', 9);
insert into album (title, artist_id) values ('War Zone, The', 4);
insert into album (title, artist_id) values ('Kings Row', 44);
insert into album (title, artist_id) values ('Real Life', 11);
insert into album (title, artist_id) values ('Comedy of Power (Ivresse du pouvoir, L'')', 29);
insert into album (title, artist_id) values ('Guns of Navarone, The', 1);
insert into album (title, artist_id) values ('Food (Jídlo)', 7);
insert into album (title, artist_id) values ('Schultze Gets the Blues', 24);
insert into album (title, artist_id) values ('Rain', 9);
insert into album (title, artist_id) values ('Razor''s Edge, The', 7);
insert into album (title, artist_id) values ('Ten Little Indians (Ein Unbekannter rechnet ab) (And Then There Were None)', 25);
insert into album (title, artist_id) values ('Scanner Darkly, A', 5);
insert into album (title, artist_id) values ('Doomed to Die', 33);
insert into album (title, artist_id) values ('Eccentricities of a Blonde-haired Girl (Singularidades de uma Rapariga Loura)', 40);
insert into album (title, artist_id) values ('Julia''s Eyes (Ojos de Julia, Los)', 6);
insert into album (title, artist_id) values ('Trip, The', 50);
insert into album (title, artist_id) values ('Hello Herman', 21);
insert into album (title, artist_id) values ('Little City', 19);
insert into album (title, artist_id) values ('Marie and Bruce', 28);
insert into album (title, artist_id) values ('Joyeux Noël (Merry Christmas)', 36);
insert into album (title, artist_id) values ('Fort McCoy', 22);
insert into album (title, artist_id) values ('Le Donk & Scor-zay-zee', 28);
insert into album (title, artist_id) values ('Teen Spirit', 7);
insert into album (title, artist_id) values ('Record of a Tenement Gentleman (Nagaya shinshiroku)', 7);
insert into album (title, artist_id) values ('O', 1);
insert into album (title, artist_id) values ('Ski Party', 19);
insert into album (title, artist_id) values ('In a Better World (Hævnen)', 13);
insert into album (title, artist_id) values ('Adam''s Apples (Adams æbler)', 49);
insert into album (title, artist_id) values ('Ruby & Quentin (Tais-toi!)', 12);
insert into album (title, artist_id) values ('Trainspotting', 42);
insert into album (title, artist_id) values ('Fat, Sick & Nearly Dead 2', 35);
insert into album (title, artist_id) values ('Four Minutes (Vier Minuten)', 50);
insert into album (title, artist_id) values ('All the Queen''s Men', 41);
insert into album (title, artist_id) values ('Experiment, The', 23);
insert into album (title, artist_id) values ('My Fellow Americans', 5);
insert into album (title, artist_id) values ('Whatever Works', 6);
insert into album (title, artist_id) values ('Lonely Place to Die, A', 19);
insert into album (title, artist_id) values ('Screaming Skull, The', 34);
insert into album (title, artist_id) values ('Harishchandrachi Factory', 20);
insert into album (title, artist_id) values ('Escape to Witch Mountain', 48);
insert into album (title, artist_id) values ('Tight Spot', 22);
insert into album (title, artist_id) values ('North Face (Nordwand)', 9);
insert into album (title, artist_id) values ('Not Safe for Work', 20);
insert into album (title, artist_id) values ('Everyday People', 37);
insert into album (title, artist_id) values ('Omen IV: The Awakening', 17);
insert into album (title, artist_id) values ('We Live Again', 38);
insert into album (title, artist_id) values ('Undercover Brother', 5);
insert into album (title, artist_id) values ('Immortals, The', 26);
insert into album (title, artist_id) values ('Days and Nights in the Forest (Aranyer Din Ratri)', 33);
insert into album (title, artist_id) values ('Logan''s Run', 5);
insert into album (title, artist_id) values ('Hamsun', 16);
insert into album (title, artist_id) values ('Together (Tillsammans)', 18);
insert into album (title, artist_id) values ('Crime of Passion', 30);
insert into album (title, artist_id) values ('Fellini: I''m a Born Liar (Fellini: Je Suis um Grand Menteur)', 47);
insert into album (title, artist_id) values ('Strange Color Of Your Body''s Tears, The (L''étrange couleur des larmes de ton corps)', 40);
insert into album (title, artist_id) values ('Fando and Lis (Fando y Lis)', 15);
insert into album (title, artist_id) values ('Cocaine Cowboys II: Hustlin'' With the Godmother', 28);
insert into album (title, artist_id) values ('One Bright Shining Moment', 3);
insert into album (title, artist_id) values ('Act of Violence', 18);
insert into album (title, artist_id) values ('The Halloween That Almost Wasn''t', 17);
insert into album (title, artist_id) values ('River Queen', 7);
insert into album (title, artist_id) values ('Thesis (Tesis)', 43);
insert into album (title, artist_id) values ('Redemption: For Robbing the Dead', 48);
insert into album (title, artist_id) values ('Coca-Cola Kid, The', 9);
insert into album (title, artist_id) values ('Sweet Liberty', 38);
insert into album (title, artist_id) values ('One Wonderful Sunday (Subarashiki nichiyobi)', 7);
insert into album (title, artist_id) values ('Jodorowsky Constellation, The (La constellation Jodorowsky)', 50);
insert into album (title, artist_id) values ('Dingo', 35);
insert into album (title, artist_id) values ('River Runs Through It, A', 13);
insert into album (title, artist_id) values ('Back-up Plan, The', 49);
insert into album (title, artist_id) values ('Milky Way, The (Voie lactée, La)', 7);
insert into album (title, artist_id) values ('They Call Me Bruce? (a.k.a. A Fistful of Chopsticks)', 42);
insert into album (title, artist_id) values ('Vampire Journals', 48);
insert into album (title, artist_id) values ('Prince of the City', 36);
insert into album (title, artist_id) values ('Grace Unplugged', 27);
insert into album (title, artist_id) values ('Gregory''s Girl', 46);
insert into album (title, artist_id) values ('Winning Season, The', 40);
insert into album (title, artist_id) values ('Where the Wild Things Are', 19);
insert into album (title, artist_id) values ('Hybrid', 28);
insert into album (title, artist_id) values ('Story of Seabiscuit, The', 3);
insert into album (title, artist_id) values ('Nanking', 11);
insert into album (title, artist_id) values ('I Spit on Your Grave', 14);
insert into album (title, artist_id) values ('A Viking Saga: The Darkest Day', 29);
insert into album (title, artist_id) values ('Presumed Innocent', 40);
insert into album (title, artist_id) values ('Devil Doll, The', 11);
insert into album (title, artist_id) values ('Nuns on the Run', 41);
insert into album (title, artist_id) values ('Accidental Spy, The (Dak miu mai shing)', 37);
insert into album (title, artist_id) values ('Hour of the Gun', 48);
insert into album (title, artist_id) values ('Animated Motion: Part 5', 41);
insert into album (title, artist_id) values ('Transporter, The', 23);
insert into album (title, artist_id) values ('Delta Force, The', 17);
insert into album (title, artist_id) values ('World, the Flesh and the Devil, The', 5);
insert into album (title, artist_id) values ('Major Movie Star', 13);
insert into album (title, artist_id) values ('Intolerable Cruelty', 18);
insert into album (title, artist_id) values ('Wild Grass (Herbes folles, Les)', 45);
insert into album (title, artist_id) values ('Terraferma', 7);
insert into album (title, artist_id) values ('Return of Martin Guerre, The (Retour de Martin Guerre, Le)', 33);
insert into album (title, artist_id) values ('Wedding Daze', 48);
insert into album (title, artist_id) values ('Step Up 2 the Streets', 9);
insert into album (title, artist_id) values ('Incredible Journey, The', 50);
insert into album (title, artist_id) values ('What Women Want', 11);
insert into album (title, artist_id) values ('Twelve Tasks of Asterix, The (Les douze travaux d''Astérix)', 5);
insert into album (title, artist_id) values ('Riley Rewind', 15);
insert into album (title, artist_id) values ('Phantom of the Opera, The', 2);
insert into album (title, artist_id) values ('Crash Reel, The', 9);
insert into album (title, artist_id) values ('Ordinary Decent Criminal', 35);
insert into album (title, artist_id) values ('Hero (Ying xiong)', 22);
insert into album (title, artist_id) values ('Blood Feast', 35);
insert into album (title, artist_id) values ('Every Other Weekend (Un week-end sur deux)', 3);
insert into album (title, artist_id) values ('Violet Tendencies', 23);
insert into album (title, artist_id) values ('Sonny Boy', 18);
insert into album (title, artist_id) values ('Gunfighter, The', 26);
insert into album (title, artist_id) values ('Organizer, The (I compagni)', 44);
insert into album (title, artist_id) values ('Whole Ten Yards, The', 35);
insert into album (title, artist_id) values ('G.I. Joe: Operation Dragonfire', 4);
insert into album (title, artist_id) values ('Tommy Boy', 16);
insert into album (title, artist_id) values ('Araya', 44);
insert into album (title, artist_id) values ('Poltergeist III', 42);
insert into album (title, artist_id) values ('Timber Falls', 8);
insert into album (title, artist_id) values ('Ratcatcher', 40);
insert into album (title, artist_id) values ('The Hanoi Hilton', 9);
insert into album (title, artist_id) values ('Anna Lucasta', 15);
insert into album (title, artist_id) values ('Killer (Tueur à gages)', 3);
insert into album (title, artist_id) values ('Gaslight', 17);
insert into album (title, artist_id) values ('For Richer or Poorer', 45);
insert into album (title, artist_id) values ('Independencia', 9);
insert into album (title, artist_id) values ('Outrage (Autoreiji)', 45);
insert into album (title, artist_id) values ('Petting Zoo', 18);
insert into album (title, artist_id) values ('8 Days to Premiere (8 päivää ensi-iltaan)', 14);
insert into album (title, artist_id) values ('The Last Word', 49);
insert into album (title, artist_id) values ('Invasion U.S.A.', 32);
insert into album (title, artist_id) values ('Interrupted Melody', 39);
insert into album (title, artist_id) values ('Two Sisters from Boston', 30);
insert into album (title, artist_id) values ('Anzio', 15);
insert into album (title, artist_id) values ('8: The Mormon Proposition', 28);
insert into album (title, artist_id) values ('Kes', 11);
insert into album (title, artist_id) values ('Red Like the Sky (Rosso come il cielo)', 32);
insert into album (title, artist_id) values ('Three Stooges, The', 36);
insert into album (title, artist_id) values ('Decasia: The State of Decay', 17);
insert into album (title, artist_id) values ('Nanny McPhee Returns (a.k.a. Nanny McPhee and the Big Bang)', 17);
insert into album (title, artist_id) values ('Eddie Murphy Delirious', 39);
insert into album (title, artist_id) values ('Sex and the City', 41);
insert into album (title, artist_id) values ('Division III: Football''s Finest', 15);
insert into album (title, artist_id) values ('Ruby in Paradise', 38);
insert into album (title, artist_id) values ('Ladyhawke', 45);
insert into album (title, artist_id) values ('Room, The', 42);
insert into album (title, artist_id) values ('Celsius 41.11: The Temperature at Which the Brain... Begins to Die', 15);
insert into album (title, artist_id) values ('11th Hour, The', 50);
insert into album (title, artist_id) values ('Knute Rockne All American', 39);
insert into album (title, artist_id) values ('Cable Guy, The', 23);
insert into album (title, artist_id) values ('Under the Same Moon (Misma luna, La)', 38);
insert into album (title, artist_id) values ('Dennis the Menace Christmas, A', 35);
insert into album (title, artist_id) values ('2001 Maniacs', 49);
insert into album (title, artist_id) values ('In the Hands of the Gods', 24);
insert into album (title, artist_id) values ('Diary of a Chambermaid', 22);
insert into album (title, artist_id) values ('Loser', 4);
insert into album (title, artist_id) values ('Dead Awake', 14);
insert into album (title, artist_id) values ('Total Recall', 18);
insert into album (title, artist_id) values ('Slave Ship', 23);
insert into album (title, artist_id) values ('Wrecking Crew, The', 32);
insert into album (title, artist_id) values ('Heart of Me, The', 39);
insert into album (title, artist_id) values ('Jackpot', 29);
insert into album (title, artist_id) values ('Keep, The', 8);
insert into album (title, artist_id) values ('Guns of Fort Petticoat, The', 50);
insert into album (title, artist_id) values ('Monsterman (Monsterimies)', 36);
insert into album (title, artist_id) values ('Eccentricities of a Blonde-haired Girl (Singularidades de uma Rapariga Loura)', 3);
insert into album (title, artist_id) values ('Let It Be', 43);


select min(id) from album;
select max(id) from album;

delete from inventory ;



insert into inventory (person_id, album_id) values (1, 145);
insert into inventory (person_id, album_id) values (1, 167);
insert into inventory (person_id, album_id) values (1, 168);
insert into inventory (person_id, album_id) values (1, 194);
insert into inventory (person_id, album_id) values (1, 216);
insert into inventory (person_id, album_id) values (1, 221);
insert into inventory (person_id, album_id) values (1, 245);
insert into inventory (person_id, album_id) values (1, 247);
insert into inventory (person_id, album_id) values (1, 265);
insert into inventory (person_id, album_id) values (1, 292);
insert into inventory (person_id, album_id) values (10, 157);
insert into inventory (person_id, album_id) values (10, 163);
insert into inventory (person_id, album_id) values (10, 168);
insert into inventory (person_id, album_id) values (10, 189);
insert into inventory (person_id, album_id) values (10, 195);
insert into inventory (person_id, album_id) values (10, 210);
insert into inventory (person_id, album_id) values (10, 236);
insert into inventory (person_id, album_id) values (10, 258);
insert into inventory (person_id, album_id) values (10, 293);
insert into inventory (person_id, album_id) values (10, 294);
insert into inventory (person_id, album_id) values (10, 311);
insert into inventory (person_id, album_id) values (10, 312);
insert into inventory (person_id, album_id) values (11, 110);
insert into inventory (person_id, album_id) values (11, 112);
insert into inventory (person_id, album_id) values (11, 116);
insert into inventory (person_id, album_id) values (11, 145);
insert into inventory (person_id, album_id) values (11, 159);
insert into inventory (person_id, album_id) values (11, 173);
insert into inventory (person_id, album_id) values (11, 192);
insert into inventory (person_id, album_id) values (11, 234);
insert into inventory (person_id, album_id) values (11, 236);
insert into inventory (person_id, album_id) values (11, 265);
insert into inventory (person_id, album_id) values (11, 336);
insert into inventory (person_id, album_id) values (12, 123);
insert into inventory (person_id, album_id) values (12, 129);
insert into inventory (person_id, album_id) values (12, 138);
insert into inventory (person_id, album_id) values (12, 341);
insert into inventory (person_id, album_id) values (12, 344);
insert into inventory (person_id, album_id) values (13, 110);
insert into inventory (person_id, album_id) values (13, 111);
insert into inventory (person_id, album_id) values (13, 129);
insert into inventory (person_id, album_id) values (13, 144);
insert into inventory (person_id, album_id) values (13, 145);
insert into inventory (person_id, album_id) values (13, 147);
insert into inventory (person_id, album_id) values (13, 153);
insert into inventory (person_id, album_id) values (13, 198);
insert into inventory (person_id, album_id) values (13, 220);
insert into inventory (person_id, album_id) values (13, 236);
insert into inventory (person_id, album_id) values (13, 239);
insert into inventory (person_id, album_id) values (13, 256);
insert into inventory (person_id, album_id) values (13, 266);
insert into inventory (person_id, album_id) values (13, 277);
insert into inventory (person_id, album_id) values (13, 346);
insert into inventory (person_id, album_id) values (14, 108);
insert into inventory (person_id, album_id) values (14, 121);
insert into inventory (person_id, album_id) values (14, 158);
insert into inventory (person_id, album_id) values (14, 178);
insert into inventory (person_id, album_id) values (14, 205);
insert into inventory (person_id, album_id) values (14, 223);
insert into inventory (person_id, album_id) values (14, 231);
insert into inventory (person_id, album_id) values (14, 255);
insert into inventory (person_id, album_id) values (14, 291);
insert into inventory (person_id, album_id) values (14, 306);
insert into inventory (person_id, album_id) values (14, 338);
insert into inventory (person_id, album_id) values (15, 114);
insert into inventory (person_id, album_id) values (15, 152);
insert into inventory (person_id, album_id) values (15, 178);
insert into inventory (person_id, album_id) values (15, 247);
insert into inventory (person_id, album_id) values (15, 335);
insert into inventory (person_id, album_id) values (16, 114);
insert into inventory (person_id, album_id) values (16, 157);
insert into inventory (person_id, album_id) values (16, 162);
insert into inventory (person_id, album_id) values (16, 215);
insert into inventory (person_id, album_id) values (16, 282);
insert into inventory (person_id, album_id) values (16, 291);
insert into inventory (person_id, album_id) values (16, 299);
insert into inventory (person_id, album_id) values (17, 106);
insert into inventory (person_id, album_id) values (17, 117);
insert into inventory (person_id, album_id) values (17, 166);
insert into inventory (person_id, album_id) values (17, 167);
insert into inventory (person_id, album_id) values (17, 173);
insert into inventory (person_id, album_id) values (17, 174);
insert into inventory (person_id, album_id) values (17, 182);
insert into inventory (person_id, album_id) values (17, 218);
insert into inventory (person_id, album_id) values (17, 277);
insert into inventory (person_id, album_id) values (17, 284);
insert into inventory (person_id, album_id) values (18, 146);
insert into inventory (person_id, album_id) values (18, 172);
insert into inventory (person_id, album_id) values (18, 316);
insert into inventory (person_id, album_id) values (18, 317);
insert into inventory (person_id, album_id) values (18, 327);
insert into inventory (person_id, album_id) values (18, 337);
insert into inventory (person_id, album_id) values (18, 344);
insert into inventory (person_id, album_id) values (19, 106);
insert into inventory (person_id, album_id) values (19, 114);
insert into inventory (person_id, album_id) values (19, 136);
insert into inventory (person_id, album_id) values (19, 139);
insert into inventory (person_id, album_id) values (19, 157);
insert into inventory (person_id, album_id) values (19, 172);
insert into inventory (person_id, album_id) values (19, 186);
insert into inventory (person_id, album_id) values (19, 203);
insert into inventory (person_id, album_id) values (19, 229);
insert into inventory (person_id, album_id) values (19, 236);
insert into inventory (person_id, album_id) values (19, 260);
insert into inventory (person_id, album_id) values (19, 262);
insert into inventory (person_id, album_id) values (19, 265);
insert into inventory (person_id, album_id) values (19, 274);
insert into inventory (person_id, album_id) values (19, 299);
insert into inventory (person_id, album_id) values (19, 334);
insert into inventory (person_id, album_id) values (2, 160);
insert into inventory (person_id, album_id) values (2, 174);
insert into inventory (person_id, album_id) values (2, 232);
insert into inventory (person_id, album_id) values (2, 301);
insert into inventory (person_id, album_id) values (2, 315);
insert into inventory (person_id, album_id) values (2, 323);
insert into inventory (person_id, album_id) values (2, 324);
insert into inventory (person_id, album_id) values (2, 339);
insert into inventory (person_id, album_id) values (20, 104);
insert into inventory (person_id, album_id) values (20, 106);
insert into inventory (person_id, album_id) values (20, 167);
insert into inventory (person_id, album_id) values (20, 178);
insert into inventory (person_id, album_id) values (20, 281);
insert into inventory (person_id, album_id) values (20, 319);
insert into inventory (person_id, album_id) values (20, 327);
insert into inventory (person_id, album_id) values (20, 329);
insert into inventory (person_id, album_id) values (20, 348);
insert into inventory (person_id, album_id) values (21, 101);
insert into inventory (person_id, album_id) values (21, 124);
insert into inventory (person_id, album_id) values (21, 126);
insert into inventory (person_id, album_id) values (21, 233);
insert into inventory (person_id, album_id) values (21, 303);
insert into inventory (person_id, album_id) values (21, 316);
insert into inventory (person_id, album_id) values (21, 319);
insert into inventory (person_id, album_id) values (21, 320);
insert into inventory (person_id, album_id) values (21, 350);
insert into inventory (person_id, album_id) values (22, 107);
insert into inventory (person_id, album_id) values (22, 148);
insert into inventory (person_id, album_id) values (22, 183);
insert into inventory (person_id, album_id) values (22, 191);
insert into inventory (person_id, album_id) values (22, 233);
insert into inventory (person_id, album_id) values (22, 331);
insert into inventory (person_id, album_id) values (22, 341);
insert into inventory (person_id, album_id) values (23, 103);
insert into inventory (person_id, album_id) values (23, 134);
insert into inventory (person_id, album_id) values (23, 171);
insert into inventory (person_id, album_id) values (23, 172);
insert into inventory (person_id, album_id) values (23, 175);
insert into inventory (person_id, album_id) values (23, 191);
insert into inventory (person_id, album_id) values (23, 203);
insert into inventory (person_id, album_id) values (23, 209);
insert into inventory (person_id, album_id) values (23, 222);
insert into inventory (person_id, album_id) values (23, 223);
insert into inventory (person_id, album_id) values (23, 227);
insert into inventory (person_id, album_id) values (23, 228);
insert into inventory (person_id, album_id) values (23, 242);
insert into inventory (person_id, album_id) values (23, 266);
insert into inventory (person_id, album_id) values (23, 335);
insert into inventory (person_id, album_id) values (23, 341);
insert into inventory (person_id, album_id) values (24, 185);
insert into inventory (person_id, album_id) values (24, 198);
insert into inventory (person_id, album_id) values (24, 286);
insert into inventory (person_id, album_id) values (24, 339);
insert into inventory (person_id, album_id) values (25, 102);
insert into inventory (person_id, album_id) values (25, 126);
insert into inventory (person_id, album_id) values (25, 166);
insert into inventory (person_id, album_id) values (25, 168);
insert into inventory (person_id, album_id) values (25, 184);
insert into inventory (person_id, album_id) values (25, 190);
insert into inventory (person_id, album_id) values (25, 227);
insert into inventory (person_id, album_id) values (25, 229);
insert into inventory (person_id, album_id) values (25, 249);
insert into inventory (person_id, album_id) values (25, 275);
insert into inventory (person_id, album_id) values (25, 298);
insert into inventory (person_id, album_id) values (25, 315);
insert into inventory (person_id, album_id) values (25, 349);
insert into inventory (person_id, album_id) values (26, 147);
insert into inventory (person_id, album_id) values (26, 163);
insert into inventory (person_id, album_id) values (26, 172);
insert into inventory (person_id, album_id) values (26, 185);
insert into inventory (person_id, album_id) values (26, 272);
insert into inventory (person_id, album_id) values (26, 312);
insert into inventory (person_id, album_id) values (26, 317);
insert into inventory (person_id, album_id) values (26, 335);
insert into inventory (person_id, album_id) values (27, 103);
insert into inventory (person_id, album_id) values (27, 129);
insert into inventory (person_id, album_id) values (27, 174);
insert into inventory (person_id, album_id) values (27, 175);
insert into inventory (person_id, album_id) values (27, 207);
insert into inventory (person_id, album_id) values (27, 235);
insert into inventory (person_id, album_id) values (27, 240);
insert into inventory (person_id, album_id) values (27, 268);
insert into inventory (person_id, album_id) values (27, 290);
insert into inventory (person_id, album_id) values (27, 294);
insert into inventory (person_id, album_id) values (27, 295);
insert into inventory (person_id, album_id) values (27, 308);
insert into inventory (person_id, album_id) values (27, 322);
insert into inventory (person_id, album_id) values (28, 197);
insert into inventory (person_id, album_id) values (28, 200);
insert into inventory (person_id, album_id) values (28, 204);
insert into inventory (person_id, album_id) values (28, 300);
insert into inventory (person_id, album_id) values (28, 313);
insert into inventory (person_id, album_id) values (28, 338);
insert into inventory (person_id, album_id) values (29, 104);
insert into inventory (person_id, album_id) values (29, 140);
insert into inventory (person_id, album_id) values (29, 155);
insert into inventory (person_id, album_id) values (29, 172);
insert into inventory (person_id, album_id) values (29, 206);
insert into inventory (person_id, album_id) values (29, 259);
insert into inventory (person_id, album_id) values (29, 318);
insert into inventory (person_id, album_id) values (29, 326);
insert into inventory (person_id, album_id) values (29, 337);
insert into inventory (person_id, album_id) values (3, 116);
insert into inventory (person_id, album_id) values (3, 128);
insert into inventory (person_id, album_id) values (3, 174);
insert into inventory (person_id, album_id) values (3, 179);
insert into inventory (person_id, album_id) values (3, 233);
insert into inventory (person_id, album_id) values (3, 238);
insert into inventory (person_id, album_id) values (3, 244);
insert into inventory (person_id, album_id) values (3, 250);
insert into inventory (person_id, album_id) values (3, 257);
insert into inventory (person_id, album_id) values (3, 259);
insert into inventory (person_id, album_id) values (3, 275);
insert into inventory (person_id, album_id) values (3, 338);
insert into inventory (person_id, album_id) values (3, 339);
insert into inventory (person_id, album_id) values (3, 343);
insert into inventory (person_id, album_id) values (3, 348);
insert into inventory (person_id, album_id) values (30, 105);
insert into inventory (person_id, album_id) values (30, 180);
insert into inventory (person_id, album_id) values (30, 185);
insert into inventory (person_id, album_id) values (30, 218);
insert into inventory (person_id, album_id) values (30, 231);
insert into inventory (person_id, album_id) values (30, 251);
insert into inventory (person_id, album_id) values (30, 258);
insert into inventory (person_id, album_id) values (30, 280);
insert into inventory (person_id, album_id) values (30, 287);
insert into inventory (person_id, album_id) values (30, 328);
insert into inventory (person_id, album_id) values (31, 146);
insert into inventory (person_id, album_id) values (31, 154);
insert into inventory (person_id, album_id) values (31, 158);
insert into inventory (person_id, album_id) values (31, 172);
insert into inventory (person_id, album_id) values (31, 182);
insert into inventory (person_id, album_id) values (31, 234);
insert into inventory (person_id, album_id) values (31, 254);
insert into inventory (person_id, album_id) values (31, 278);
insert into inventory (person_id, album_id) values (31, 291);
insert into inventory (person_id, album_id) values (31, 310);
insert into inventory (person_id, album_id) values (31, 346);
insert into inventory (person_id, album_id) values (31, 350);
insert into inventory (person_id, album_id) values (32, 101);
insert into inventory (person_id, album_id) values (32, 119);
insert into inventory (person_id, album_id) values (32, 150);
insert into inventory (person_id, album_id) values (32, 151);
insert into inventory (person_id, album_id) values (32, 174);
insert into inventory (person_id, album_id) values (32, 219);
insert into inventory (person_id, album_id) values (32, 257);
insert into inventory (person_id, album_id) values (32, 273);
insert into inventory (person_id, album_id) values (32, 317);
insert into inventory (person_id, album_id) values (32, 318);
insert into inventory (person_id, album_id) values (32, 328);
insert into inventory (person_id, album_id) values (33, 102);
insert into inventory (person_id, album_id) values (33, 107);
insert into inventory (person_id, album_id) values (33, 144);
insert into inventory (person_id, album_id) values (33, 145);
insert into inventory (person_id, album_id) values (33, 154);
insert into inventory (person_id, album_id) values (33, 158);
insert into inventory (person_id, album_id) values (33, 162);
insert into inventory (person_id, album_id) values (33, 177);
insert into inventory (person_id, album_id) values (33, 292);
insert into inventory (person_id, album_id) values (33, 337);
insert into inventory (person_id, album_id) values (34, 127);
insert into inventory (person_id, album_id) values (34, 134);
insert into inventory (person_id, album_id) values (34, 135);
insert into inventory (person_id, album_id) values (34, 161);
insert into inventory (person_id, album_id) values (34, 168);
insert into inventory (person_id, album_id) values (34, 176);
insert into inventory (person_id, album_id) values (34, 242);
insert into inventory (person_id, album_id) values (34, 249);
insert into inventory (person_id, album_id) values (34, 264);
insert into inventory (person_id, album_id) values (34, 325);
insert into inventory (person_id, album_id) values (35, 102);
insert into inventory (person_id, album_id) values (35, 115);
insert into inventory (person_id, album_id) values (35, 135);
insert into inventory (person_id, album_id) values (35, 177);
insert into inventory (person_id, album_id) values (35, 183);
insert into inventory (person_id, album_id) values (35, 187);
insert into inventory (person_id, album_id) values (35, 255);
insert into inventory (person_id, album_id) values (35, 286);
insert into inventory (person_id, album_id) values (35, 293);
insert into inventory (person_id, album_id) values (35, 344);
insert into inventory (person_id, album_id) values (35, 350);
insert into inventory (person_id, album_id) values (36, 152);
insert into inventory (person_id, album_id) values (36, 153);
insert into inventory (person_id, album_id) values (36, 170);
insert into inventory (person_id, album_id) values (36, 178);
insert into inventory (person_id, album_id) values (36, 219);
insert into inventory (person_id, album_id) values (36, 242);
insert into inventory (person_id, album_id) values (36, 253);
insert into inventory (person_id, album_id) values (36, 261);
insert into inventory (person_id, album_id) values (36, 270);
insert into inventory (person_id, album_id) values (36, 275);
insert into inventory (person_id, album_id) values (36, 301);
insert into inventory (person_id, album_id) values (36, 314);
insert into inventory (person_id, album_id) values (36, 340);
insert into inventory (person_id, album_id) values (37, 109);
insert into inventory (person_id, album_id) values (37, 193);
insert into inventory (person_id, album_id) values (37, 215);
insert into inventory (person_id, album_id) values (37, 246);
insert into inventory (person_id, album_id) values (37, 257);
insert into inventory (person_id, album_id) values (37, 285);
insert into inventory (person_id, album_id) values (37, 323);
insert into inventory (person_id, album_id) values (37, 328);
insert into inventory (person_id, album_id) values (38, 119);
insert into inventory (person_id, album_id) values (38, 126);
insert into inventory (person_id, album_id) values (38, 143);
insert into inventory (person_id, album_id) values (38, 171);
insert into inventory (person_id, album_id) values (38, 194);
insert into inventory (person_id, album_id) values (38, 241);
insert into inventory (person_id, album_id) values (38, 267);
insert into inventory (person_id, album_id) values (38, 298);
insert into inventory (person_id, album_id) values (38, 330);
insert into inventory (person_id, album_id) values (38, 335);
insert into inventory (person_id, album_id) values (38, 336);
insert into inventory (person_id, album_id) values (39, 167);
insert into inventory (person_id, album_id) values (39, 173);
insert into inventory (person_id, album_id) values (39, 183);
insert into inventory (person_id, album_id) values (39, 238);
insert into inventory (person_id, album_id) values (39, 239);
insert into inventory (person_id, album_id) values (39, 240);
insert into inventory (person_id, album_id) values (39, 330);
insert into inventory (person_id, album_id) values (4, 143);
insert into inventory (person_id, album_id) values (4, 152);
insert into inventory (person_id, album_id) values (4, 207);
insert into inventory (person_id, album_id) values (4, 229);
insert into inventory (person_id, album_id) values (4, 296);
insert into inventory (person_id, album_id) values (4, 345);
insert into inventory (person_id, album_id) values (40, 101);
insert into inventory (person_id, album_id) values (40, 132);
insert into inventory (person_id, album_id) values (40, 134);
insert into inventory (person_id, album_id) values (40, 166);
insert into inventory (person_id, album_id) values (40, 173);
insert into inventory (person_id, album_id) values (40, 221);
insert into inventory (person_id, album_id) values (40, 230);
insert into inventory (person_id, album_id) values (40, 236);
insert into inventory (person_id, album_id) values (40, 248);
insert into inventory (person_id, album_id) values (40, 253);
insert into inventory (person_id, album_id) values (40, 261);
insert into inventory (person_id, album_id) values (40, 284);
insert into inventory (person_id, album_id) values (41, 105);
insert into inventory (person_id, album_id) values (41, 144);
insert into inventory (person_id, album_id) values (41, 168);
insert into inventory (person_id, album_id) values (41, 200);
insert into inventory (person_id, album_id) values (41, 202);
insert into inventory (person_id, album_id) values (41, 240);
insert into inventory (person_id, album_id) values (41, 245);
insert into inventory (person_id, album_id) values (41, 272);
insert into inventory (person_id, album_id) values (41, 302);
insert into inventory (person_id, album_id) values (41, 323);
insert into inventory (person_id, album_id) values (42, 120);
insert into inventory (person_id, album_id) values (42, 141);
insert into inventory (person_id, album_id) values (42, 229);
insert into inventory (person_id, album_id) values (42, 232);
insert into inventory (person_id, album_id) values (42, 240);
insert into inventory (person_id, album_id) values (42, 255);
insert into inventory (person_id, album_id) values (42, 273);
insert into inventory (person_id, album_id) values (42, 307);
insert into inventory (person_id, album_id) values (42, 329);
insert into inventory (person_id, album_id) values (43, 136);
insert into inventory (person_id, album_id) values (43, 137);
insert into inventory (person_id, album_id) values (43, 151);
insert into inventory (person_id, album_id) values (43, 190);
insert into inventory (person_id, album_id) values (43, 197);
insert into inventory (person_id, album_id) values (43, 198);
insert into inventory (person_id, album_id) values (43, 209);
insert into inventory (person_id, album_id) values (43, 217);
insert into inventory (person_id, album_id) values (43, 220);
insert into inventory (person_id, album_id) values (43, 240);
insert into inventory (person_id, album_id) values (43, 244);
insert into inventory (person_id, album_id) values (43, 258);
insert into inventory (person_id, album_id) values (43, 277);
insert into inventory (person_id, album_id) values (43, 284);
insert into inventory (person_id, album_id) values (43, 347);
insert into inventory (person_id, album_id) values (44, 120);
insert into inventory (person_id, album_id) values (44, 128);
insert into inventory (person_id, album_id) values (44, 178);
insert into inventory (person_id, album_id) values (44, 186);
insert into inventory (person_id, album_id) values (44, 234);
insert into inventory (person_id, album_id) values (44, 244);
insert into inventory (person_id, album_id) values (44, 282);
insert into inventory (person_id, album_id) values (44, 333);
insert into inventory (person_id, album_id) values (44, 337);
insert into inventory (person_id, album_id) values (44, 342);
insert into inventory (person_id, album_id) values (44, 343);
insert into inventory (person_id, album_id) values (45, 108);
insert into inventory (person_id, album_id) values (45, 109);
insert into inventory (person_id, album_id) values (45, 125);
insert into inventory (person_id, album_id) values (45, 166);
insert into inventory (person_id, album_id) values (45, 172);
insert into inventory (person_id, album_id) values (45, 209);
insert into inventory (person_id, album_id) values (45, 253);
insert into inventory (person_id, album_id) values (45, 324);
insert into inventory (person_id, album_id) values (46, 102);
insert into inventory (person_id, album_id) values (46, 106);
insert into inventory (person_id, album_id) values (46, 147);
insert into inventory (person_id, album_id) values (46, 151);
insert into inventory (person_id, album_id) values (46, 189);
insert into inventory (person_id, album_id) values (46, 262);
insert into inventory (person_id, album_id) values (46, 299);
insert into inventory (person_id, album_id) values (46, 300);
insert into inventory (person_id, album_id) values (46, 318);
insert into inventory (person_id, album_id) values (47, 111);
insert into inventory (person_id, album_id) values (47, 158);
insert into inventory (person_id, album_id) values (47, 172);
insert into inventory (person_id, album_id) values (47, 225);
insert into inventory (person_id, album_id) values (47, 230);
insert into inventory (person_id, album_id) values (47, 243);
insert into inventory (person_id, album_id) values (47, 263);
insert into inventory (person_id, album_id) values (47, 274);
insert into inventory (person_id, album_id) values (47, 280);
insert into inventory (person_id, album_id) values (47, 339);
insert into inventory (person_id, album_id) values (48, 101);
insert into inventory (person_id, album_id) values (48, 134);
insert into inventory (person_id, album_id) values (48, 154);
insert into inventory (person_id, album_id) values (48, 165);
insert into inventory (person_id, album_id) values (48, 184);
insert into inventory (person_id, album_id) values (48, 201);
insert into inventory (person_id, album_id) values (48, 216);
insert into inventory (person_id, album_id) values (48, 304);
insert into inventory (person_id, album_id) values (48, 330);
insert into inventory (person_id, album_id) values (48, 336);
insert into inventory (person_id, album_id) values (48, 347);
insert into inventory (person_id, album_id) values (49, 104);
insert into inventory (person_id, album_id) values (49, 113);
insert into inventory (person_id, album_id) values (49, 119);
insert into inventory (person_id, album_id) values (49, 155);
insert into inventory (person_id, album_id) values (49, 176);
insert into inventory (person_id, album_id) values (49, 202);
insert into inventory (person_id, album_id) values (49, 242);
insert into inventory (person_id, album_id) values (49, 250);
insert into inventory (person_id, album_id) values (49, 260);
insert into inventory (person_id, album_id) values (49, 261);
insert into inventory (person_id, album_id) values (49, 270);
insert into inventory (person_id, album_id) values (49, 283);
insert into inventory (person_id, album_id) values (49, 284);
insert into inventory (person_id, album_id) values (49, 321);
insert into inventory (person_id, album_id) values (49, 324);
insert into inventory (person_id, album_id) values (5, 123);
insert into inventory (person_id, album_id) values (5, 143);
insert into inventory (person_id, album_id) values (5, 149);
insert into inventory (person_id, album_id) values (5, 167);
insert into inventory (person_id, album_id) values (5, 177);
insert into inventory (person_id, album_id) values (5, 217);
insert into inventory (person_id, album_id) values (5, 234);
insert into inventory (person_id, album_id) values (5, 265);
insert into inventory (person_id, album_id) values (5, 294);
insert into inventory (person_id, album_id) values (5, 295);
insert into inventory (person_id, album_id) values (5, 313);
insert into inventory (person_id, album_id) values (5, 337);
insert into inventory (person_id, album_id) values (50, 131);
insert into inventory (person_id, album_id) values (50, 159);
insert into inventory (person_id, album_id) values (50, 202);
insert into inventory (person_id, album_id) values (50, 240);
insert into inventory (person_id, album_id) values (50, 276);
insert into inventory (person_id, album_id) values (50, 289);
insert into inventory (person_id, album_id) values (50, 304);
insert into inventory (person_id, album_id) values (50, 329);
insert into inventory (person_id, album_id) values (6, 115);
insert into inventory (person_id, album_id) values (6, 177);
insert into inventory (person_id, album_id) values (6, 195);
insert into inventory (person_id, album_id) values (7, 169);
insert into inventory (person_id, album_id) values (7, 175);
insert into inventory (person_id, album_id) values (7, 207);
insert into inventory (person_id, album_id) values (7, 225);
insert into inventory (person_id, album_id) values (7, 243);
insert into inventory (person_id, album_id) values (7, 244);
insert into inventory (person_id, album_id) values (7, 271);
insert into inventory (person_id, album_id) values (7, 274);
insert into inventory (person_id, album_id) values (7, 350);
insert into inventory (person_id, album_id) values (8, 111);
insert into inventory (person_id, album_id) values (8, 184);
insert into inventory (person_id, album_id) values (8, 197);
insert into inventory (person_id, album_id) values (8, 231);
insert into inventory (person_id, album_id) values (8, 269);
insert into inventory (person_id, album_id) values (8, 286);
insert into inventory (person_id, album_id) values (8, 348);
insert into inventory (person_id, album_id) values (9, 123);
insert into inventory (person_id, album_id) values (9, 147);
insert into inventory (person_id, album_id) values (9, 171);
insert into inventory (person_id, album_id) values (9, 202);
insert into inventory (person_id, album_id) values (9, 206);
insert into inventory (person_id, album_id) values (9, 283);
insert into inventory (person_id, album_id) values (9, 340);
insert into inventory (person_id, album_id) values (9, 349);


